name: deploy

on:
    push:
        branches:
            - "main"

jobs:
    deploy:
        name: deploy_to_vps
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: create .env
              run: |
                  touch .env
                  echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
                  echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
                  echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
                  echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
                  echo "SECRET=${{ secrets.SECRET }}" >> .env
            - name: create ssh_config
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_KEY }}
                  name: ssh_config
                  known_hosts: ${{ secrets.KNOWN_HOSTS }}
                  config: |
                      Host vps
                      HostName ${{ secrets.HOST_NAME }}
                      User ${{ secrets.USER }}
                      Port ${{ secrets.PORT }}
                      IdentityFile ~/.ssh/ssh_config
                      StrictHostKeyChecking no
            - name: install
              run: |
                  ssh vps "cd ./tumaguro_backend/; git pull origin main; docker compose down; docker compose up --build -d;"
